import "./globals.css";
import { Inter } from "next/font/google";
import { Roboto } from "next/font/google";
import { Poppins } from "next/font/google";
import localFont from "next/font/local";
import 'leaflet/dist/leaflet.css';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({ subsets: ["latin"], weight: ["300", "400", "500", "700", "900"] });
const poppins = Poppins({ subsets: ["latin"], weight: ["300", "400", "500", "600", "700", "800", "900"] });
const calSans = localFont({
  src: "../fonts/CalSans-SemiBold.woff2", 
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${roboto.className} ${poppins.className} ${calSans.className}`}>
        {children}
      </body>
    </html>
  );
}
